/* TASK 1*/
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

/* TASK 2*/
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

/* TASK 3*/
SELECT SALARY, FIRST_NAME FROM EMPLOYEES WHERE SALARY > 6000;

/*TASK 4*/
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE SALARY > 20000;


/* TASK 5*/
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE SALARY > 6000;

/* TASK 6*/
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE EMPLOYEES ADD COLUMN ANNUAL_CTC INT;
UPDATE EMPLOYEES SET ANNUAL_CTC = SALARY*12;

/* TASK 7*/

ALTER TABLE EMPLOYEES ADD NEW_SALARY INT;
UPDATE EMPLOYEES SET NEW_SALARY = SALARY*1.2 WHERE SALARY BETWEEN 2000 AND 15000;
UPDATE EMPLOYEES SET NEW_SALARY = SALARY*1.1 WHERE SALARY BETWEEN 16000 AND 20000;
UPDATE EMPLOYEES SET NEW_SALARY = SALARY*1.05 WHERE SALARY BETWEEN 21000 AND 25000;

SELECT SALARY, NEW_SALARY FROM EMPLOYEES;

/* TASK 8*/
SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME, '      ', LAST_NAME) AS FULL_NAME, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

/*TASK 9*/
SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME, '      ', LAST_NAME) AS FULL_NAME, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
/* TASK 10*/

SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, EMPLOYEE_ID FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

/* TASK 11*/
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 100 ORDER BY SALARY DESC LIMIT 3;
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 110 ORDER BY SALARY DESC LIMIT 3;
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 ORDER BY SALARY DESC LIMIT 3;
/* TASK 12*/

SELECT DEPARTMENT_ID, ANNUAL_CTC FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 ORDER BY ANNUAL_CTC DESC LIMIT 1;
SELECT DEPARTMENT_ID, ANNUAL_CTC FROM EMPLOYEES WHERE DEPARTMENT_ID = 80 ORDER BY ANNUAL_CTC DESC LIMIT 1;
SELECT DEPARTMENT_ID, ANNUAL_CTC FROM EMPLOYEES WHERE DEPARTMENT_ID = 20 ORDER BY ANNUAL_CTC DESC LIMIT 1;

/* TASK 13*/
SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK%';


/*TASK 14*/
SELECT COUNT(EMPLOYEE_ID) AS CLERK_EMPLOYEE_COUNT, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK%';


/*TASK 15*/

SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_COUNT, DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID; 

/* TASK 16*/
SELECT AVG(SALARY) AS AVERAGE_SALARY, DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;


/*TASK 17*/
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY BETWEEN 7000 AND 10000 GROUP BY DEPARTMENT_ID;

/*TASK 18*/
SELECT CONCAT(FIRST_NAME, '      ', LAST_NAME) AS FULL_NAME, HIRE_DATE, (CURRENT_DATE- HIRE_DATE)/365 AS EXPERIENCE FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;

