CREATE DATABASE IF NOT EXISTS COMPANY;
CREATE TABLE COMPANY.EMPLOYEE_DETAIL
(
EMPLOYEE_NO INT PRIMARY KEY,
DOB DATETIME,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
GENDER VARCHAR(50),
HIRE_DATE DATE
);

DESC COMPANY.EMPLOYEE_DETAILS; 

USE COMPANY;

CREATE TABLE COMPANY.DEPARTMENT
(
DEPARTMENT_NO VARCHAR(50) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50),
EMPLOYEE_NO INT,
FOREIGN KEY (EMPLOYEE_NO) 
REFERENCES COMPANY.EMPLOYEE_DETAIL(EMPLOYEE_NO)
);


INSERT INTO COMPANY.EMPLOYEE_DETAIL (EMPLOYEE_NO, DOB, FIRST_NAME, LAST_NAME, GENDER, HIRE_DATE)
VALUES (101, '2000-04-06 23:24:25', 'KOMURAM', 'BHEEM', 'MALE', '2020-04-06'),
       (102, '1999-08-08 08:32:32', 'PAWAR', 'RAMA KRISHNA', 'FEMALE', '2019-08-08');  
       
INSERT INTO COMPANY.DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, EMPLOYEE_NO)
VALUES(111, 'SALES', 101),
	  (222, 'JUNIOR ASST', 102);
      
SET SQL_SAFE_UPDATES = 0;
      
UPDATE COMPANY.DEPARTMENT SET  DEPARTMENT_NAME = 'SALES AND FINANCE' WHERE DEPARTMENT_NAME = 'SALES';
SELECT * FROM COMPANY.DEPARTMENT;
UPDATE COMPANY.DEPARTMENT SET DEPARTMENT_NAME = 'MANAGERS' WHERE DEPARTMENT_NAME = 'JUNIOR ASST';
DELETE FROM COMPANY.DEPARTMENT WHERE EMPLOYEE_NO = 101;

