CREATE DATABASE IF NOT EXISTS CAR_SALE;
CREATE TABLE CAR_SALE.SALESPERSON
(
SALES_ID INT,
FIRST_NAME VARCHAR(50),
CITY VARCHAR(50),
COMMISSION_RATE INT
);

CREATE TABLE CAR_SALE.CUSTOMER
(
COSTOMER_NAME VARCHAR(50), 
MOBILE_NUMBER INT
);

CREATE TABLE CAR_SALE.ORDERS
(
ORDER_ID INT,
ORDER_NAME VARCHAR(50)
);

/*TASK 3 - POPULATE THE DATA*/
DESC CAR_SALE.SALESPERSON;

INSERT INTO CAR_SALE.SALESPERSON (SALES_ID, FIRST_NAME, CITY, COMMISSION_RATE)
VALUES (1002, 'PETER', 'LONDON', 12),
        (1002, 'PETER', 'LONDON', 12),
        (1003, 'RIFKIN', 'BARCELONA', 15),
        (1004, 'JUDITH', 'LONDON', 11),
        (1008, 'JOHN', 'LONDON', 0),
        (1009, 'CHARLES', 'FLORIDA',NULL ),
        (1009, 'CHARLES', 'FLORIDA',NULL ),
        (1004, 'JUDITH', 'LONDON', 11),
        (1004, 'JUDITH', 'LONDON', 11),
        (1003, 'RIFKIN', 'BARCELONA', 15),
        (1003, 'RIFKIN', 'BARCELONA', 15),
        (1003, 'RIFKIN', 'BARCELONA', 15),
        (1001, 'SERRES', 'SAN JOSE',13),
        (1001, 'SERRES', 'SAN JOSE',13),
        (1009, 'CHARLES', 'FLORIDA', NULL),
        (1008, 'JOHN', 'LONDON', 0),
        (1008, 'JOHN', 'LONDON', 0),
        (1008, 'JOHN', 'LONDON', 0);
        
DESC CAR_SALE.SALESPERSON;
SELECT * FROM CAR_SALE.SALESPERSON;