SELECT * FROM S3_CAR_SALES_DATA.CUSTOMER_TABLE;
SELECT * FROM ORDERS_TABLE;
SELECT * FROM SALESPERSON;


/* TASK 1*/

SELECT S.S_SALESID, S.S_NAME, O.ORDERID FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID
INNER JOIN ORDERS_TABLE AS O ON O.CUSTOMERID = C.C_CUSTOMERID;



/*TASK 2*/

SELECT S.S_NAME, CONCAT(C_FIRSTNAME,'     ', C_LASTNAME) AS 'COSTOMER NAME'
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID;

/*TASK 3*/

SELECT COUNT(SALESID), S.S_SALESID 
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID 
GROUP BY S_SALESID HAVING COUNT(SALESID) > 1;

/* TASK 4*/

SELECT COUNT(SALESID), S.S_SALESID, S.S_NAME 
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID 
GROUP BY S.S_SALESID ORDER BY COUNT(SALESID) DESC;

/* TASK 5*/

SELECT * FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID
INNER JOIN ORDERS_TABLE AS O ON O.CUSTOMERID = C.C_CUSTOMERID
WHERE S_NAME = 'PEEI';

/* TASK 6*/

SELECT S.S_NAME, CONCAT(C_FIRSTNAME, '      ', C_LASTNAME) AS CUSTOMER_NAME, C_CITY AS COMMON_CITY 
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID
WHERE S_CITY = C_CITY;

/* TASK 7*/

SELECT S.S_NAME, CONCAT(C_FIRSTNAME, '      ', C_LASTNAME) AS CUSTOMER_NAME, C_CITY, S_CITY
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID 
INNER JOIN ORDERS_TABLE AS O ON O.CUSTOMERID = C.C_CUSTOMERID
WHERE S_CITY != C_CITY;                                         

/* TASK 8*/

SELECT S_NAME, COMMISSION_RATE, S_CITY FROM SALESPERSON WHERE S_CITY = 'LONDON';

/* TASK 9*/

CREATE VIEW COMMISSION_DATA AS
SELECT S_NAME, COMMISSION_RATE, S_SALESID FROM  SALESPERSON WHERE COMMISSION_RATE > 12;
SELECT * FROM COMMISSION_DATA;

/* TASK 10*/
SELECT S.S_NAME, S.S_SALESID
FROM SALESPERSON AS S INNER JOIN CUSTOMER_TABLE AS C ON S.S_SALESID = C.SALESID
WHERE S.S_CITY != C.C_CITY;



